#Set working directory
WORKDIR: "$HOME/scratch/stephensiSmallRNA-november2018-mayvInf"

#Set sample names
SAMPLES: ["C_D14_Rep-1_S16",
        "C_D14_Rep-2_S17",
        "C_D14_Rep-3_S18",
        "C_D2_Rep-1_S10",
        "C_D2_Rep-2_S11",
        "C_D2_Rep-3_S12",
        "C_D7_Rep-1_S13",
        "C_D7_Rep-2_S14",
        "C_D7_Rep-3_S15",
        "V_D14_Rep-1_S7",
        "V_D14_Rep-2_S8",
        "V_D14_Rep-3_S9",
        "V_D2_Rep-1_S1",
        "V_D2_Rep-2_S2",
        "V_D2_Rep-3_S3",
        "V_D7_Rep-1_S4",
        "V_D7_Rep-2_S5",
        "V_D7_Rep-3_S6"]

#Set group ID
GROUP_ID: ["1", "1", "1", "1", "1", "1", "1", "1", "1", "2", "2", "2", "2", "2", "2", "2", "2", "2"]
GROUP_MAX: "2"

#Set important paths
GENOME: "genomes/anophelesStephensiScaffoldAstel2.fa"
GENOME_ANNOTATION: "genomes/anophelesStephensiBaseFeaturesAstel2.3.gtf"
GO_MAPPINGS: "genomes/goMappings.csv"
#Close species are Aedes aegypti, Culex, Drosophila melanogaster, Bombyx mori, Apis mellifera, Acyrthosiphon pisum
CLOSE_MATURE: "genomes/combinedCloseMature.fa"
#All Anopheles gambiae miRNAs used for same species
SAME_MATURE: "genomes/anGamb-miRNA-mature.fa"
SAME_PRE: "genomes/anGamb-miRNA-stemLoop.fa"

#Define important paths
ADAPTERS: "/storage/work/cah422/adapters/adapters.fa"
GATK: "/storage/work/cxb585/bin/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar"
PICARD: "/storage/work/cxb585/bin/picard-2.10.10/picard.jar"
TRIMMOMATIC: "/storage/work/cxb585/bin/Trimmomatic-0.36/trimmomatic-0.36.jar"

#Select modules to load
MODULES: ["bamtools", "bcftools", "tophat", "gatk", "picard", "python", "samtools", "trimmomatic", "vcftools"]
